on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

name: test
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-13
          - os: macos-14
          - os: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: gcc -o macos_iconv_bug ${{ startsWith(matrix.os, 'macos') && '-liconv' || '' }} macos_iconv_bug.c

      - name: Test
        run: |
          set +e
          ./macos_iconv_bug
          status=$?
          hexdump result.txt
          exit $status

  test-freebsd:
    name: test-freebsd
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - release: "13.4"
          - release: "14.2"
          - release: "15.0"
    steps:
      - uses: actions/checkout@v4

      - name: Test on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: ${{ matrix.release }}
          prepare: |
            pkg install -y lang/gcc
          run: |
            # We want to delete libiconv by "pkg delete -y libiconv" but we cannot.
            # Because rsync depends on it and we use rsync later.
            rm /usr/local/include/iconv.h

            gcc -o macos_iconv_bug macos_iconv_bug.c
            ldd macos_iconv_bug

            set +e
            ./macos_iconv_bug
            status=$?
            hexdump result.txt
            exit $status

  test-netbsd:
    name: test-netbsd
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - release: "9.4"
          - release: "10.1"
    steps:
      - uses: actions/checkout@v4

      - name: Test on Netbsd
        uses: vmactions/netbsd-vm@v1
        with:
          usesh: true
          release: ${{ matrix.release }}
          run: |
            gcc -o macos_iconv_bug macos_iconv_bug.c
            ldd macos_iconv_bug

            set +e
            ./macos_iconv_bug
            status=$?
            hexdump result.txt
            exit $status

  test-openbsd:
    name: test-openbsd
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - release: "7.6"
    steps:
      - uses: actions/checkout@v4

      - name: Test on OpenBSD
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          release: ${{ matrix.release }}
          run: |
            clang -o macos_iconv_bug macos_iconv_bug.c
            ldd macos_iconv_bug

            set +e
            ./macos_iconv_bug
            status=$?
            hexdump result.txt
            exit $status
