on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

name: test
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-13
          - os: macos-14
          - os: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: gcc -o macos_iconv_bug ${{ startsWith(matrix.os, 'macos') && '-liconv' || '' }} macos_iconv_bug.c

      - name: Test
        run: |
          set +e
          ./macos_iconv_bug
          status=$?
          hexdump result.txt
          exit $status
